config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/newinvitation', to: 'invitations#new'
  resources :invitations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def home
    render html: "hello, USER!"
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
 def show
    @invitation = Invitation.find(params[:id])
  end 

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    if @invitation.save
      flash[:success] = "Welcome to the WEDINGQU App!" 
      redirect_to @invitation
    else
      render 'new'
   end 
   end

private

  def invitation_params
    params.require(:invitation).permit(:tittle, :venue, :start_at, :end_at)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "WedingQu"
	 if page_title.empty?
	    base_title
		else
			page_title + " | " + base_title
		end
	end 
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/invitations/_form.html.erb
<!--%= form_with(model: invitation) do |form| %>
  <!% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><!%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <!% invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <!% end %>
      </ul>
    </div>
  <!% end %>

  <div class="field">
    <!%= form.label :tittle %>
    <!%= form.text_field :tittle %>
  </div>

  <div class="field">
    <!%= form.label :venue %>
    <!%= form.text_field :venue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<!% end %>

app/views/invitations/edit.html.erb
<!--<h1>Editing Invitation</h1>

<!%= render 'form', invitation: @invitation %>

<!%= link_to 'Show', @invitation %> |
<!%= link_to 'Back', invitations_path %> 

app/views/invitations/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Venue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.tittle %></td>
        <td><%= invitation.venue %></td>
        <td><!%= link_to 'Show', invitation %></td>
        <td><!%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><!%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <!% end %>
  </tbody>
</table>

app/views/invitations/new.html.erb
<% provide(:title, 'New Invitation') %>
<h1>New Invitation</h1>

	<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @invitation, local: true) do |f| %>
 			<!--%= render 'shared/error_messages', object: f.object %-->

			<%= f.label :tittle %>
			<%= f.text_field :tittle, class: 'form-control' %>

			<%= f.label :venue %>
			<%= f.text_field :venue, class: 'form-control' %>

			<%= f.label :start_at %>
			<%= f.datetime_field :start_at, class: 'form-control' %>

			<%= f.label :end_at %>
			<%= f.datetime_field :end_at, class: 'form-control' %>

			<%= f.submit "Create invitation", class: "btn- primary" %>
		<% end %>
	</div>
</div>

app/views/invitations/show.html.erb
<% provide(:title, @invitation.tittle) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
		
			<%= @invitation.tittle %>
			<br/>
		  	<%= @invitation.venue %>
		  	<br/>
		  
		  	<%= @invitation.start_at %>
		  	<br/>
		  	<%= @invitation.end_at %>


		  
		</section>
	</aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
	The <a>Weding App</a>
	by <a>Yodi Eprilian</a>
 </small>
<nav>
	<ul>
		<li><%= link_to "About", about_path %></li>
 	    <li><%= link_to "Contact", contact_path %></li>
	</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light">
	<div class="container">
		<%= link_to "WedingQu", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right" style="color">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Create Invitation", newinvitation_path, class: 'btn-primary' %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j s">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks- track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j s">
      </script>
    <![endif]-->
    <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
 </body>
</html>

app/views/shared/_error_messages.html.erb
<!--% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
		The form contains <!%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<!% object.errors.full_messages.each do |msg| %>
		 <li><%= msg %></li>
		<!% end %>
		</ul>
	</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a>, part of the
  <a href="https://www.learnenough.com/">Learn Enough</a> family of
  tutorials, is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="https://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<div class="center">
	
</div>
	